config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
  
  get 'game', to: 'game#index'
  get 'game/play', to: 'game#play'
  post 'game/play', to: 'game#discard'
  
  get 'game/result', to: 'game#result'
  post 'game/result', to: 'game#tsumo'
  
  get 'game/play_renew', to: 'game#play_renew'
  post 'game/renew_ajax', to: 'game#renew_ajax'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tile.rb
class Tile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :danger
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    
  end
  
  def play
    if !Tile.all().exists?
      create_mahjong_tile
    end
    tileAll = Tile.all()
    
    mode_select = params[:mode_select]
    init_hands = get_init_hands(mode_select)
    
    @rest_tiles = tileAll.sample(init_hands + 30)
    
    if Rails.cache.exist?('discard_tiles')
      Rails.cache.clear('discard_tiles')
    end
    
    @hand_tiles = @rest_tiles.slice!(0..(init_hands - 2))
    @next_tile = @rest_tiles.slice!(0)
    
    Rails.cache.write('hand_tiles', @hand_tiles)
    Rails.cache.write('rest_tiles', @rest_tiles)
    
    if Rails.cache.exist?('discard_tiles')
      @discard_tiles = Rails.cache.read('discard_tiles')
    else
      @discard_tiles = Array.new()
    end
    #binding.pry()
  end
  
  # 牌の種類をデータベースに登録。
  # キーワードajax(非同期通信) rails jsファイル
  def discard
    @hand_tiles = Rails.cache.read('hand_tiles')
    @rest_tiles = Rails.cache.read('rest_tiles')
    @discard_tiles = Array.new()
    @next_tile = @rest_tiles.slice!(0)
    
    #binding.pry()
    if @next_tile.nil?
      @next_tile = Tile.find(params[:last_tile_id])
      @discard_tiles = Rails.cache.read('discard_tiles')
      
      flash.now[:danger] = "残りツモ回数がありません。あなたの負けです。"
    else
      @select_tile = Tile.find(params[:tile_id])
      if @hand_tiles.include?(@select_tile)
        @hand_tiles.delete(@select_tile)
        @hand_tiles.append(Tile.find(params[:last_tile_id]))
      end
      
      if Rails.cache.exist?('discard_tiles')
        @discard_tiles = Rails.cache.read('discard_tiles')
      end
      @discard_tiles.append(@select_tile)
      #binding.pry()
      
      Rails.cache.write('hand_tiles', @hand_tiles)
      Rails.cache.write('rest_tiles', @rest_tiles)
      Rails.cache.write('discard_tiles', @discard_tiles)
    end
    render :play
  end
  
  def result
  end
  
  def tsumo
    hand_tiles = Tile.find(params[:hand]).sort()
    if canWin(hand_tiles)
      redirect_to '/game/result', success: 'ツモ上がりです！'
    else
      redirect_to '/game/result', danger: 'チョンボとなります！'
    end
  end
  
  def play_renew
    if !Tile.all().exists?
      create_mahjong_tile
    end
    tileAll = Tile.all()
    
    # mode_select = params[:mode_select]
    # init_hands = get_init_hands(mode_select)
    init_hands = 14
    
    # 牌山
    @rest_tiles = tileAll.sample(init_hands + 30)
    
    # 手牌
    @hand_tiles = @rest_tiles.slice!(0..(init_hands - 2))
    @draw_tile = @rest_tiles.slice!(0)
  end
  
  def renew_ajax
    hand_tiles = Tile.find(params[:tsumo][:hand].split(",")).sort()
    # p hand_tiles
    
    # mode_select = params[:mode_select]
    # init_hands = get_init_hands(mode_select)
    init_hands = 14
    
    # 牌山
    @rest_tiles = Tile.all().sample(init_hands + 30)
    
    # 手牌
    @hand_tiles = @rest_tiles.slice!(0..(14 - 2))
    @draw_tile = @rest_tiles.slice!(0)
    if canWin(hand_tiles)
      flash.now[:success] = 'ツモ上がりです！'
      render :play_renew
    else
      flash.now[:danger] = 'チョンボとなります！'
      render :play_renew
    end
  end
  
  private
  def create_mahjong_tile
    ['m', 'p', 's', 'z'].each do |suit_num|
      for suit_value in 1..9 do
        loop_count = 0
        while loop_count < 4
          if suit_num != 'z'
            Tile.create(suit: suit_num, value: suit_value)
          elsif suit_value < 8
            Tile.create(suit: suit_num, value: suit_value)
          end
          loop_count += 1
        end
      end
    end
  end
  
  def get_init_hands(mode_text)
    case mode_text
    when 'easy' then
      return 8
    when 'normal' then
      return 11
    when 'hard' then
      return 14
    end
  end
  
  def canWin(hand_tiles)
    # 手牌から雀頭候補リストを作成。
    # 雀頭を取り除き、面子候補を割り出す。
    hand_tiles_array = hand_tiles.map{ |tile| tile.value.to_s + tile.suit }
    pair_list = hand_tiles_array.filter{ |tile| hand_tiles_array.count(tile) > 1}.uniq
    
    # 七対子(seven pairs)判定。
    if pair_list.length == 7
      return true
    end
    
    # 4面子1雀頭判定ロジック
    # 1. 雀頭候補を割り出す。(oair)
    # 2. 刻子候補を割り出す。(triplets)
    # 3. 順子候補を割り出す。(sequences)
    pair_list.each do |pair_tile|
      # 雀頭を除いた手牌。
      tile_group = hand_tiles_array.clone
      tile_group[hand_tiles_array.index(pair_tile), 2] = []
      if isAllGroup(tile_group)
        return true
      end
    end
    
    return false
  end
  
  def isAllGroup(tile_group)
    # 刻子(同じ牌が3枚)リスト。
    triplets_list = tile_group.filter{ |tile| tile_group.count(tile) > 2}.uniq
    triplets_all_subset = [[]]
    
    # 刻子の和集合作成(刻子がない場合でも作成)。
    triplets_list.each do |triplets|
      triplets_all_subset_copy = triplets_all_subset.clone()
      triplets_all_subset_copy.each do |triplets_subset|
        triplets_all_subset.append [triplets].concat(triplets_subset)
      end
    end
    
    triplets_all_subset.each do |triplets_subset|
      tile_group_copy = tile_group.clone()
      
      # 刻子を取り除く。
      triplets_subset.each do |triplets|
        if tile_group_copy.include?(triplets)
          tile_group_copy[tile_group_copy.index(triplets), 3] = []
        end
      end
      
      # 順子の組み合わせ。
      while tile_group_copy.length > 0 do
        first_tile = tile_group_copy.first
        
        # 字牌は刻子のみ成り立つ。
        if first_tile.include?("z")
          break
        end
        
        next_sequences_tile = (first_tile[0].to_i + 1).to_s + first_tile[1]
        if !tile_group_copy.include?(next_sequences_tile)
          break
        end
        
        next_after_sequences_tile = (next_sequences_tile[0].to_i + 1).to_s + first_tile[1]
        if !tile_group_copy.include?(next_after_sequences_tile)
          break
        end
        
        # 順子を取り除く。
        tile_group_copy.delete_at tile_group_copy.index(first_tile)
        tile_group_copy.delete_at tile_group_copy.index(next_sequences_tile)
        tile_group_copy.delete_at tile_group_copy.index(next_after_sequences_tile)
      end
      
      # 4面子揃っている。
      if tile_group_copy.length == 0
        return true
      end
    end
    
    return false
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def ripai(tehai)
    return tehai.sort()
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/game/index.html.erb
<h1>難易度を選んでください</h1>
<div>
  <%= link_to "やさしい", game_play_path(mode_select: "easy"), class: 'btn btn-primary' %>
  <%= link_to "ふつう", game_play_path(mode_select: "normal"), class: 'btn btn-primary' %>
  <%= link_to "むずかしい", game_play_path(mode_select: "hard"), class: 'btn btn-primary' %>
</div>

app/views/game/play.html.erb
<h1></h1>
<div>
  <div>
    <p>残りツモ回数
      <b class='color-red'><%= @rest_tiles.size %></b>
    </p>
  </div>
  
  <div class="bg-info bg-opacity-25" id="discard-area">
    <div>
      <h3>捨て牌エリア</h3>
    </div>
    <% @discard_tiles.each_with_index do |pai, i| %>
      <% if i % 6 == 0 && i != 0 %>
        <br>
      <% end %>
      <%= image_tag "MahjongPai/p_#{pai.suit + pai.value.to_s}_1.gif", id: "discard" + pai.id.to_s %>
    <% end %>
  </div>
  
  <div class="hand-area bg-warning bg-opacity-25">
    <div>
      <h3>手牌エリア</h3>
    </div>
    <% @hand_tiles = ripai(@hand_tiles) %>
    <% @hand_tiles.each_with_index do |pai, i| %>
      <%= form_with url: game_play_path(tile_id: pai.id, last_tile_id: @next_tile.id), method: :post, local: true do |form| %>
        <%= link_to image_tag("MahjongPai/p_#{pai.suit + pai.value.to_s}_0.gif"), '#', onclick: 'this.closest("form").submit(); return false;', id: "hand_tiles" + pai.id.to_s %>
      <% end %>
    <% end %>
    　<%= form_with url: game_play_path(tile_id: @next_tile.id, last_tile_id: @next_tile.id), method: :post, local: true do |form| %>
        <%= link_to image_tag("MahjongPai/p_#{@next_tile.suit + @next_tile.value.to_s}_0.gif"), '#', onclick: 'this.closest("form").submit(); return false;', id: "hand_tiles" + @next_tile.id.to_s %>
      <% end %>
  </div>
</div>
<%#= javascript_include_tag "game.js" %>

<%= button_to "和了", game_result_path(hand: @hand_tiles.append(@next_tile)), method: :post, class: 'btn btn-primary', data: { turbo: false } %>

app/views/game/play_renew.html.erb
<h1>javascript動作のゲーム画面</h1>
<div id="rest-area">
  <h3>牌山エリア</h3>
  
  <%#= idはデータベースのユニークIDをセット。%>
  <ol class="tile-line" id="rest-line">
    <% @rest_tiles.each_with_index do |pai, i| %>
      <li>
        <%= image_tag "MahjongPai/p_bk_1.gif", id: pai.id, data: { imgdraw: image_path("MahjongPai/p_#{pai.suit + pai.value.to_s}_0.gif"), imgdiscard: image_path("MahjongPai/p_#{pai.suit + pai.value.to_s}_1.gif") } %>
      </li>
    <% end %>
  </ol>
</div>

<div id="discard-area">
  <h3>捨て牌エリア</h3>
  <ol class="tile-line" id="discard-line"></ol>
</div>

<div id="hand-area">
  <h3>手牌エリア</h3>
  
  <ol class="tile-line" id="hand-line">
    <% @hand_tiles = ripai(@hand_tiles) %>
    <% @hand_tiles.each do |pai| %>
      <li>
        <%= image_tag "MahjongPai/p_#{pai.suit + pai.value.to_s}_0.gif", id: pai.id, data: { img: image_path("MahjongPai/p_#{pai.suit + pai.value.to_s}_1.gif")} %>
      </li>
    <% end %>
    <li class="draw-tile">
      <%= image_tag "MahjongPai/p_#{@draw_tile.suit + @draw_tile.value.to_s}_0.gif", id: @draw_tile.id, data: { img: image_path("MahjongPai/p_#{@draw_tile.suit + @draw_tile.value.to_s}_1.gif")} %>
    </li>
  </ol>
</div>
<%= form_with url: game_renew_ajax_path, scope: :tsumo, method: :post, data: { turbo: false } do |form| %>
  <%= form.hidden_field :hand, value: @hand_tiles.append(@draw_tile).sort.map { |tile| tile.id }.join(",") %>
  <%= form.button "和了", class: 'btn btn-primary' %>
<% end %>

<%= javascript_import_module_tag "mahjong" %>

app/views/game/result.html.erb
<div>
  <%= link_to "もう一度遊ぶ", game_path, class: 'btn btn-primary' %>
  <%= link_to "トップページに戻る", root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoloMahjong</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
  <% end %>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/pages/index.html.erb
<%= link_to "1人麻雀を始める", game_path, class: 'btn btn-primary' %>
<%= link_to "1人麻雀を始める(javascript制作用)", game_play_renew_path, class: 'btn btn-primary' %>